Repository inxudianz/Project-Famili, pull requests merged in 2020-11, with the labels that each got.

#109 [PFSP3-0002] Add Build Config and Flex
  Podfile
  Podfile.lock
Labels: feature

#110 [PFSP3-0004] XcodeGen Integration
  .github/workflows/mainProject.yml
  Component/Component-project.yml
  Component/Component.xcodeproj/project.pbxproj
  Component/Component.xcodeproj/xcshareddata/xcschemes/Component.xcscheme
  Laundron-User/LUCodable/LUCodable-project.yml
  Laundron-User/LUCodable/LUCodable.xcodeproj/project.pbxproj
  Laundron-User/LUCoordinatorHandler/LUAppCoordinator/LUAppCoordinator-project.yml
  Laundron-User/LUCoordinatorHandler/LUAppCoordinator/LUAppCoordinator.xcodeproj/project.pbxproj
  Laundron-User/LUCoordinatorHandler/LUCoordinator/LUCoordinator-project.yml
  Laundron-User/LUCoordinatorHandler/LUCoordinator/LUCoordinator.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth-project.yml
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuthTests/LUAuthTests.swift
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuthTests/LoginTests.swift
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuthTests/RegisterTests.swift
  Laundron-User/LUFeature/LUAuth/LUAuthNetwork/LUAuthNetwork-project.yml
  Laundron-User/LUFeature/LUAuth/LUAuthNetwork/LUAuthNetwork.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUHome/LUHome/LUHome-project.yml
  Laundron-User/LUFeature/LUHome/LUHome/LUHome.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUHome/LUHomeNetwork/LUHomeNetwork-project.yml
  Laundron-User/LUFeature/LUHome/LUHomeNetwork/LUHomeNetwork.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder-project.yml
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUOrder/LUOrderNetwork/LUOrderNetwork-project.yml
  Laundron-User/LUFeature/LUOrder/LUOrderNetwork/LUOrderNetwork.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfile-project.yml
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfile.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUProfile/LUProfileNetwork/LUProfileNetwork-project.yml
  Laundron-User/LUFeature/LUProfile/LUProfileNetwork/LUProfileNetwork.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUSample/LUSample/LUSample-project.yml
  Laundron-User/LUFeature/LUSample/LUSample/LUSample.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUSample/LUSampleNetwork/LUSampleNetwork-project.yml
  Laundron-User/LUFeature/LUSample/LUSampleNetwork/LUSampleNetwork.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUSplash/LUSplash/LUSplash-project.yml
  Laundron-User/LUFeature/LUSplash/LUSplash/LUSplash.xcodeproj/project.pbxproj
  Laundron-User/LUFeature/LUSplash/LUSplashNetwork/LUSplashNetwork-project.yml
  Laundron-User/LUFeature/LUSplash/LUSplashNetwork/LUSplashNetwork.xcodeproj/project.pbxproj
  Laundron-User/LUHandler/LUHandler-project.yml
  Laundron-User/LUHandler/LUHandler.xcodeproj/project.pbxproj
  Laundron-User/LUMain/LUMain-project.yml
  Laundron-User/LUMain/LUMain.xcodeproj/project.pbxproj
  Laundron-User/LUNetwork/LUNetwork-project.yml
  Laundron-User/LUNetwork/LUNetwork.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  Project-Famili.xcworkspace/contents.xcworkspacedata
  xcodegen.sh
Labels: feature

#115 [PFCMP-0008] Chat Bubble
  Component/Component/ChatBubble/FamiliChatBubble.swift
  Component/Component/ChatBubble/FamiliChatBubbleConstant.swift
Labels: component

#117 [PFCMP-0011] Empty View
  Component/Component/View/EmptyView/FamiliEmptyView.swift
  Component/Component/View/EmptyView/FamiliEmptyViewConstant.swift
Labels: component

#116 [PFDOC-0010] Unit Testing Update
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuthTests/LoginTests.swift
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuthTests/RegisterTests.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHomeTests/HomeLandingTests.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHomeTests/NotificationTests.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfileTests/EditProfileTests.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfileTests/HelpCenterDetailTests.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfileTests/HelpCenterTests.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfileTests/PrivacyPolicyTests.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfileTests/ProfileLandingTests.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfileTests/TermsOfServiceTests.swift
Labels: documentation

#118 [PFCMP-0010] Network Failure View #98
  Component/Component/View/NetworkFailureView/NetworkFailureView.swift
  Component/Component/View/NetworkFailureView/NetworkFailureView.xib
Labels: component

#121 [PFDOC-0009] Color Styles
  Laundron-User/LUHandler/LUHandler/ColorManager/ColorManager.swift
Labels: documentation

#123 [PFBF3-0001] Fix missing images
  Component/Component/Button/DualButton/FamiliDualButton.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder/OrderLanding/Cell/OrderLandingHeaderView.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder/OrderLanding/Cell/OrderLandingTableViewCell.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder/OrderLanding/Cell/OrderLandingTableViewCell.xib
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfile/ProfileLanding/ProfileLandingCell/ProfileLandingCell.swift
  Laundron-User/LUFeature/LUProfile/LUProfile/LUProfile/ProfileLanding/ProfileLandingController.swift
Labels: bugfix

#120 [PFCMP-0009] Modal View
  Component/Component/View/FamiliModalView/FamiliModalConstant.swift
  Component/Component/View/FamiliModalView/FamiliModalView.swift
Labels: component

#122 [PFBF3-0002] Notification Refactor
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/Coordinator/HomeCoordinator.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationMessageCell/HomeNotificationMessageTableViewCell.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationMessageCell/HomeNotificationMessageTableViewCell.xib
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationMessageDataSource.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationNewsCell/HomeNotificationNewsTableViewCell.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationNewsCell/HomeNotificationNewsTableViewCell.xib
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationNewsDataSource.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationProtocol.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationViewController.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationViewController.xib
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationViewModel+Network.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationViewModel.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/Resources/HomeNotificationConstant.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/Notification/NotificationDataSource.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/Notification/NotificationNewsViewModel+Network.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHomeTests/NotificationTests.swift
Labels: bugfix

#125 [PFSP3-0007] Update Workspace
  Component/Component/Button/LoginButton/LoginButton.swift
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth/Login/LoginViewController.swift
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth/Login/LoginViewController.xib
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth/Register/RegisterViewController.swift
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth/Register/RegisterViewController.xib
  Laundron-User/LUFeature/LUAuth/LUAuth/LUAuth/Resources/AuthConstant.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeLanding/HomeLandingProtocol.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeLanding/HomeLandingViewController.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeLanding/HomeLandingViewModel.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeLanding/Service Cell/ServiceCollectionViewCell.swift
  Laundron-User/LUFeature/LUHome/LUHome/LUHomeTests/HomeLandingTests.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder/OrderLanding/OrderLandingProtocol.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder/OrderLanding/OrderLandingViewController.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrder/OrderLanding/OrderLandingViewModel.swift
  Laundron-User/LUFeature/LUOrder/LUOrder/LUOrderTests/OrderLandingTests.swift
  Project-Famili.xcworkspace/contents.xcworkspacedata
Labels: feature
