Repository inxudianz/Project-Famili, pull requests merged in 2020-07, with the labels that each got.

#11 [PFDOC-001] Issue & Pull Request Template
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation

#13 [PFSP0-0001] AppCoordinator
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/App/AppCoordinator+FeatureCoordinator.swift
  MainApp/MainApp/Coordinator/App/AppCoordinator.swift
  MainApp/MainApp/Coordinator/App/Appcoordinator+BuildConfiguration.swift
  MainApp/MainApp/Coordinator/App/BuildConfiguration.swift
  MainApp/MainApp/Coordinator/AppCoordinator.swift
  MainApp/MainApp/Coordinator/Coordinator.swift
  MainApp/MainApp/Coordinator/Feature/Home/HomeCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Home/HomeCoordinatorProtocol.swift
  MainApp/MainApp/Coordinator/Feature/Profile/ProfileCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Profile/ProfileCoordinatorProtocol.swift
  MainApp/MainApp/SceneDelegate.swift
  MainApp/MainAppTests/Feature/HomeTests.swift
Labels: feature

#16 [PFSP0-0002] Network Stub
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Debug/Undefined.swift
  MainApp/MainApp/Feature/Home/HomeViewModel.swift
  MainApp/MainApp/Network/NetworkError.swift
  MainApp/MainApp/Network/NetworkService.swift
  MainApp/MainApp/Network/Path/BasePath.swift
  MainApp/MainAppTests/Feature/HomeTests.swift
Labels: feature

#18 [PFSP0-0003] App Structure
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/App/AppCoordinator+FeatureCoordinator.swift
  MainApp/MainApp/Coordinator/App/AppCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Sample/SampleHome/SampleHomeCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Sample/SampleHome/SampleHomeCoordinatorProtocol.swift
  MainApp/MainApp/Coordinator/Feature/Sample/SampleProfile/SampleProfileCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Sample/SampleProfile/SampleProfileCoordinatorProtocol.swift
  MainApp/MainApp/Feature/Home/HomeDetail/HomeDetailProtocol.swift
  MainApp/MainApp/Feature/Profile/ProfileDetail/ProfileDetailProtocol.swift
  MainApp/MainApp/Feature/Profile/ProfileProtocol.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeDetail/SampleHomeDetailProtocol.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeDetail/SampleHomeDetailViewController.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeDetail/SampleHomeDetailViewController.xib
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeDetail/SampleHomeDetailViewModel.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeProtocol.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewController.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewController.xib
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewModel+Network.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewModel.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileDetail/SampleProfileDetailProtocol.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileDetail/SampleProfileDetailViewController.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileDetail/SampleProfileDetailViewController.xib
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileDetail/SampleProfileDetailViewModel.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileProtocol.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileViewController.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileViewController.xib
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileViewModel.swift
  MainApp/MainApp/SceneDelegate.swift
  MainApp/MainAppTests/Feature/Sample/SampleHomeTests.swift
Labels: feature

#25 [PFDOC-0002] App Documentation
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/AppDelegate.swift
  MainApp/MainApp/Config/Debug.xcconfig
  MainApp/MainApp/Coordinator/App/AppCoordinator+FeatureCoordinator.swift
  MainApp/MainApp/Coordinator/App/AppCoordinator.swift
  MainApp/MainApp/Debug/Log.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewController.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileDetail/SampleProfileDetailViewController.swift
  MainApp/MainApp/Feature/Sample/SampleProfile/SampleProfileViewController.swift
  MainApp/MainApp/Network/NetworkService.swift
  MainApp/MainApp/Resources/Main.xcassets/AppIcon.appiconset/Contents.json
  MainApp/MainApp/Resources/Main.xcassets/Contents.json
  MainApp/MainApp/SceneDelegate.swift
  MainApp/MainApp/ViewController.swift
Labels: documentation

#31 [PFCMP-0003] Custom TextField
  Component/Component.xcodeproj/project.pbxproj
  Component/Component/Extension/UIColor.swift
  Component/Component/Textfield/FamiliTextField.swift
  Component/Component/Textfield/FamiliTextFieldConstant.swift
  MainApp/MainApp.xcodeproj/project.pbxproj
Labels: component

#32 Hotfix fonts not being uploaded
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Info.plist
  MainApp/MainApp/Resources/Fonts/Inter-Black.ttf
  MainApp/MainApp/Resources/Fonts/Inter-Bold.ttf
  MainApp/MainApp/Resources/Fonts/Inter-ExtraBold.ttf
  MainApp/MainApp/Resources/Fonts/Inter-ExtraLight.ttf
  MainApp/MainApp/Resources/Fonts/Inter-Light.ttf
  MainApp/MainApp/Resources/Fonts/Inter-Medium.ttf
  MainApp/MainApp/Resources/Fonts/Inter-Regular.ttf
  MainApp/MainApp/Resources/Fonts/Inter-SemiBold.ttf
  MainApp/MainApp/Resources/Fonts/Inter-Thin.ttf
Labels: component
