Repository inxudianz/Project-Famili, pull requests merged in 2020-08, with the labels that each got.

#34 [PFCMP-0002] Custom UI Button
  Component/Component.xcodeproj/project.pbxproj
  Component/Component/Button/FamiliButton/FamiliButton.swift
Labels: component

#35 [PFSP1-0005] Firebase Integration
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/App/AppCoordinator+Firebase.swift
  MainApp/MainApp/Coordinator/App/AppCoordinator.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewController.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewModel+Network.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewModel.swift
  MainApp/MainApp/FeatureNetwork/SampleNetwork/SampleNetwork.swift
  MainApp/MainApp/Network/Codable/Entities/EmptyModel.swift
  MainApp/MainApp/Network/Codable/Entities/SampleModel.swift
  MainApp/MainApp/Network/Codable/Response/EmptyResponse.swift
  MainApp/MainApp/Network/Codable/Response/SampleResponse.swift
  MainApp/MainApp/Network/HTTPTask.swift
  MainApp/MainApp/Network/NetworkService.swift
  MainApp/MainApp/Network/NetworkType.swift
  MainApp/MainApp/Network/Path/BasePath.swift
  MainApp/MainApp/Network/Path/FeaturePath/Sample/SamplePath.swift
  MainApp/MainApp/Network/Path/FeaturePath/Sample/SampleSubPath.swift
  MainApp/MainApp/Network/Service/SampleService.swift
  MainApp/MainApp/Resources/AppDelegate.swift
  MainApp/MainApp/Resources/Handler/FirebaseHandler.swift
  MainApp/MainApp/Resources/Info.plist
  MainApp/MainApp/Resources/SceneDelegate.swift
  MainApp/MainAppTests/Feature/Sample/SampleHomeTests.swift
Labels: feature

#30 [PFSP1-0001][PFSP1-0002] Initial Screen, Login Screen
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/Feature/Login/LoginCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Login/LoginCoordinatorProtocol.swift
  MainApp/MainApp/Coordinator/Feature/Splash/InitialScreenCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Splash/InitialScreenCoordinatorProtocol.swift
  MainApp/MainApp/Feature/Login/LoginProtocol.swift
  MainApp/MainApp/Feature/Login/LoginViewController.swift
  MainApp/MainApp/Feature/Login/LoginViewController.xib
  MainApp/MainApp/Feature/Login/LoginViewModel.swift
  MainApp/MainApp/Feature/Splash/InitialScreenProtocol.swift
  MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
  MainApp/MainApp/Feature/Splash/InitialScreenViewController.xib
  MainApp/MainApp/Feature/Splash/InitialScreenViewModel.swift
  MainApp/MainApp/FeatureNetwork/LoginNetwork/LoginNetwork.swift
  MainApp/MainApp/Network/Codable/Entities/LoginModel.swift
  MainApp/MainApp/Network/Codable/Response/LoginResponse.swift
  MainApp/MainApp/Network/Path/FeaturePath/Auth/LoginPath.swift
  MainApp/MainApp/Network/Path/FeaturePath/Auth/LoginSubPath.swift
  MainApp/MainApp/Network/Service/LoginService.swift
Labels: feature

#37 [PSFP1-0004][PFSP1-0008] Profile Landing Screen, Profile Detail
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/Feature/Profile/ProfileCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Profile/ProfileCoordinatorConstant.swift
  MainApp/MainApp/Coordinator/Feature/Profile/ProfileCoordinatorProtocol.swift
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileController.swift
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileController.xib
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileProtocol.swift
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileViewModel.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingCell/ProfileLandingCell.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingCell/ProfileLandingCell.xib
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingController.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingController.xib
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingProtocol.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingViewModel.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileTableViewSection.swift
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Call.imageset/Call.png
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Call.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Edit Profile.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Edit Profile.imageset/Edit.png
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Help Center.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Help Center.imageset/Help.png
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Mail.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Mail.imageset/Mail.png
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Privacy Policy.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Privacy Policy.imageset/Privacy.png
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Rate Us.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Rate Us.imageset/Star.png
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Terms of Service.imageset/Contents.json
  MainApp/MainApp/Feature/Profile/Resources/ProfileAsset.xcassets/Terms of Service.imageset/Info.png
  MainApp/MainApp/FeatureNetwork/ProfileNetwork/ProfileNetwork.swift
  MainApp/MainApp/Network/Codable/Entities/ProfileModel.swift
  MainApp/MainApp/Network/Codable/Response/ProfileResponse.swift
  MainApp/MainApp/Network/Service/ProfilePath.swift
  MainApp/MainApp/Network/Service/ProfileService.swift
  MainApp/MainApp/Network/Service/ProfileSubPath.swift
Labels: feature

#39 [PFSP1-0003] Register Screen
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/App/AppCoordinator+FeatureCoordinator.swift
  MainApp/MainApp/Coordinator/App/AppCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Register/RegisterCoordinator.swift
  MainApp/MainApp/Coordinator/Feature/Register/RegisterCoordinatorProtocol.swift
  MainApp/MainApp/Feature/Register/Register.xcassets/Contents.json
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_fb.imageset/Contents.json
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_fb.imageset/image 2.png
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_fb.imageset/image 2@2x.png
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_fb.imageset/image 2@3x.png
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_google.imageset/Contents.json
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_google.imageset/image 1.png
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_google.imageset/image 1@2x.png
  MainApp/MainApp/Feature/Register/Register.xcassets/ic_google.imageset/image 1@3x.png
  MainApp/MainApp/Feature/Register/RegisterPopUpViewController.swift
  MainApp/MainApp/Feature/Register/RegisterPopUpViewController.xib
  MainApp/MainApp/Feature/Register/RegisterProtocol.swift
  MainApp/MainApp/Feature/Register/RegisterViewController.swift
  MainApp/MainApp/Feature/Register/RegisterViewController.xib
  MainApp/MainApp/Feature/Register/RegisterViewModel+Network.swift
  MainApp/MainApp/Feature/Register/RegisterViewModel.swift
  MainApp/MainApp/FeatureNetwork/SampleNetwork/SampleNetwork.swift
  MainApp/MainApp/Network/Codable/Entities/RegisterModel.swift
  MainApp/MainApp/Network/Codable/Response/RegisterResponse.swift
  MainApp/MainApp/Network/Path/FeaturePath/Register/RegisterNetwork.swift
  MainApp/MainApp/Network/Path/FeaturePath/Register/RegisterPath.swift
  MainApp/MainApp/Network/Service/RegisterService.swift
  MainApp/MainApp/Resources/SceneDelegate.swift
Labels: feature

#36 [PFSP1-0006][PFSP1-0007] Google Sign-In Integration, Facebook Sign-In Integration
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Coordinator/App/AppCoordinator+GoogleSDK.swift
  MainApp/MainApp/Coordinator/App/AppCoordinator.swift
  MainApp/MainApp/Feature/Sample/SampleHome/SampleHomeViewController.swift
  MainApp/MainApp/Network/Service/SampleService.swift
  MainApp/MainApp/Resources/AppDelegate.swift
  MainApp/MainApp/Resources/Handler/FacebookSDKHandler.swift
  MainApp/MainApp/Resources/Handler/FirebaseHandler.swift
  MainApp/MainApp/Resources/Handler/GoogleSDKHandler.swift
  MainApp/MainApp/Resources/Info.plist
  MainApp/MainApp/Resources/SceneDelegate.swift
  Podfile
  Podfile.lock
Labels: feature

#67 [PFDOC-0003] Unit Testing - Initial Screen
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainAppTests/Feature/Splash/InitialScreenTests.swift
Labels: documentation

#68 [PFBF2-0009] Clear All Button
  Component/Component.xcodeproj/project.pbxproj
  Component/Component/Component.xcassets/Contents.json
  Component/Component/Component.xcassets/icon_close.imageset/Contents.json
  Component/Component/Component.xcassets/icon_close.imageset/close-o.png
  Component/Component/Textfield/FamiliTextField.swift
  Component/Component/Textfield/FamiliTextFieldConstant.swift
Labels: bugfix

#69 [PFDOC-0004] Unit Testing - Login #54
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainAppTests/Feature/Splash/InitialScreenTests.swift
  MainApp/MainAppTests/Feature/Splash/LoginTests.swift
Labels: documentation

#72 [PFDOC-0007] Unit Testing - Profile Detail
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Feature/Profile/ProfileLanding/EditProfileTests.swift
Labels: documentation

#71 [PFDOC-0006] Unit Testing - Profile
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingTests.swift
Labels: documentation

#70 [PFDOC-0005] Unit Testing - Register #55
  MainApp/MainApp.xcodeproj/project.pbxproj
  MainApp/MainApp/Feature/Auth/Register/RegisterTests.swift
Labels: documentation

#75 [PFBF2-0001] Initial Screen Alignment bugfix #45
  MainApp/MainApp/Feature/Splash/InitialScreenViewController.xib
Labels: bugfix

#73 [PFBF2-0005] Login Here and Register Here Behaviour Different #49
  MainApp/MainApp/Feature/Auth/Login/LoginViewController.xib
  MainApp/MainApp/Feature/Auth/Register/RegisterViewController.xib
Labels: bugfix

#78 [PFBF2-0004] Profile Selection Stay Highlighted after Backing
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingController.swift
Labels: bugfix

#76 [PFBF2-0007] Register Have No Way To Hide Keyboard #51
  MainApp/MainApp/Feature/Auth/Register/RegisterViewController.swift
  MainApp/MainApp/Feature/Auth/Register/RegisterViewController.xib
Labels: bugfix

#77 [PFBF2-0003] Edit Profile Have no Validation
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileController.swift
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileController.xib
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileProtocol.swift
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileViewModel.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/EditProfileTests.swift
  MainApp/MainApp/Feature/Profile/Resources/ProfileConstant.swift
Labels: bugfix

#79 [PFBF2-0008] Font not using Inter on some pages
  MainApp/MainApp/Feature/Auth/Login/LoginViewController.swift
  MainApp/MainApp/Feature/Auth/Register/RegisterViewController.swift
  MainApp/MainApp/Feature/Profile/EditProfile/EditProfileController.swift
  MainApp/MainApp/Feature/Profile/ProfileLanding/ProfileLandingController.swift
  MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
  MainApp/MainApp/Resources/Handler/FontManager.swift
Labels: bugfix
